import os
import random
from typing import Any, Dict

import networkx as nx
import pandapower as pp
from pandapower.diagnostic import diagnostic

from gridalyn.foundation.data import datasets
from gridalyn.twin.core.graph import PowerGridGraph
from gridalyn.interfaces.viz.interactive import GridPlotter
from gridalyn.simulation.simulators.powerflow.builder import PandapowerGridBuilder
from gridalyn.assets.datagen.data.weather import download_tmy, select_cold_day
from gridalyn.simulation.simulators.agents.fleet import make_buildings, simulate_buildings


class PowerFlowAnalysisDatagen:
    def __init__(self, input_file: str, output_dir: str = "examples/generated/outputs"):
        self.input_file = input_file
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)
        self.pg_graph = PowerGridGraph()
        self.pp_net = None
        self.plotter = None
        self.config = {
            "loads": {
                "max_load_per_building": 10,
                "diversity_factor": 1.01  # Extracted from our empirical evaluate_transformer_diversity analysis
            },
            "buses": {
                "lv": {"voltage_kv": 0.4, "type": "b"},
                "mv": {"voltage_kv": 20.0, "type": "b"},
                "hv": {"voltage_kv": 110.0, "type": "b"},
            },
            "lines": {
                "lv": {"std_type": "94-AL1/15-ST1A 0.4", "min_length_km": 0.001},
                "mv": {"std_type": "149-AL1/24-ST1A 10.0", "min_length_km": 0.001},
                "hv": {"std_type": "149-AL1/24-ST1A 10.0", "min_length_km": 0.001},
            },
            "transformers": {
                "lv_mv": {"std_type": "0.63 MVA 20/0.4 kV", "capacity_kva": 250, "utilization_margin": 0.80},
                "mv_hv": {"std_type": "25 MVA 110/20 kV", "capacity_kva": 25000},
            },
        }

    def run(self, force_rebuild: bool = False):
        import pickle
        import os
        
        cache_pg = os.path.join(self.output_dir, "pg_graph_cache.pkl")
        cache_pp = os.path.join(self.output_dir, "pp_net_cache.pkl")
        
        # In validate mode (force_rebuild), we recompute. Otherwise attempt cache.
        if not force_rebuild and os.path.exists(cache_pg) and os.path.exists(cache_pp):
            print("====== Stage 1: Loading Cached Grid Generation ======")
            try:
                with open(cache_pg, "rb") as f:
                    self.pg_graph = pickle.load(f)
                with open(cache_pp, "rb") as f:
                    self.pp_net = pickle.load(f)
                print(f"Loaded Cached Grid: {len(self.pp_net.bus)} buses, {len(self.pp_net.line)} lines.")
            except ModuleNotFoundError as exc:
                print(f"Ignoring stale cache generated by an old package layout: {exc}")
                force_rebuild = True

        if force_rebuild or not os.path.exists(cache_pg) or not os.path.exists(cache_pp):
            print("====== Stage 1: Spatial Grid Generation ======")
            self.extract_building_data()
            self.create_grid_graphs()
            self.build_pandapower_model()
            
            with open(cache_pg, "wb") as f:
                pickle.dump(self.pg_graph, f)
            with open(cache_pp, "wb") as f:
                pickle.dump(self.pp_net, f)
            print("Cached spatial grid and pandapower model to disk for future runs.")
        
        print("\n====== Stage 2 & 3: Monte Carlo Stochastic Simulation (Serial Benchmark) ======")
        import time
        t_start = time.time()
        N_REALIZATIONS = 30
        import numpy as np
        
        self.mc_ext_p_mw = []
        self.mc_max_line = []
        self.mc_mean_line = []
        self.mc_raw_p_mw = []
        
        # Fetch weather ONCE
        print("Fetching Datagen weather data (TMY) for the ensemble...")
        tmy = download_tmy()
        cold_day = select_cold_day(tmy)
        
        # Accumulators for spatial worst cases
        self.mc_spatial_v = []
        self.mc_spatial_line = []
        self.mc_spatial_trafo = []
        
        for sim in range(N_REALIZATIONS):
            print(f"\n--- Probabilistic Realization {sim+1}/{N_REALIZATIONS} ---")
            self.inject_datagen_loads(cold_day, seed=42+sim)
            ow = self.run_power_flow()
            
            # Store timeseries curves for stochastic shadow banding
            self.mc_ext_p_mw.append(ow.output["res_ext_grid.p_mw"].sum(axis=1).abs().values)
            self.mc_max_line.append(ow.output["res_line.loading_percent"].max(axis=1).values)
            self.mc_mean_line.append(ow.output["res_line.loading_percent"].mean(axis=1).values)
            self.mc_raw_p_mw.append(self.raw_datagen_p_mw.values[:96])
            
            self.mc_spatial_v.append(ow.output["res_bus.vm_pu"].values)
            self.mc_spatial_line.append(ow.output["res_line.loading_percent"].values)
            self.mc_spatial_trafo.append(ow.output["res_trafo.loading_percent"].values)
            
        print("\n====== Aggregating Dimensional Stochastic Matrices ======")
        mc_spatial_v_np = np.array(self.mc_spatial_v)
        mc_spatial_line_np = np.array(self.mc_spatial_line)
        mc_spatial_trafo_np = np.array(self.mc_spatial_trafo)
        
        # Establish the absolute stochastic bound for every single grid node natively
        self.pp_net.res_bus["vm_pu"] = mc_spatial_v_np.min(axis=(0, 1))  
        self.pp_net.res_line["loading_percent"] = mc_spatial_line_np.max(axis=(0, 1)) 
        self.pp_net.res_trafo["loading_percent"] = mc_spatial_trafo_np.max(axis=(0, 1)) 
        
        t_end = time.time()
        print(f"\n[BENCHMARK] Serial 30x Simulation Execution Time: {t_end - t_start:.2f} seconds")
        
        self.verify_grid_stats()
        self.visualize_results()
        self.plot_stochastic_results()

    def extract_building_data(self):
        self.pg_graph.extract_building_centers_and_areas(self.input_file)
        building_data_output_filepath = os.path.join(
            self.output_dir, "buildings_data.json"
        )
        self.pg_graph.export_building_data_to_json(building_data_output_filepath)
        print(f"Building data extracted ({len(self.pg_graph.building_data)} buildings).")

    def create_grid_graphs(self):
        max_load_per_building = self.config["loads"]["max_load_per_building"]
        diversity_factor = self.config["loads"]["diversity_factor"]
        
        lv_transformer_config = self.config["transformers"]["lv_mv"]
        mv_lv_transformer_capacity = lv_transformer_config["capacity_kva"]
        capacity_utilization_factor = lv_transformer_config["utilization_margin"]
        
        self.pg_graph.create_lv_graph(
            max_load_per_building, 
            mv_lv_transformer_capacity,
            capacity_utilization_factor,
            diversity_factor
        )
        self.pg_graph.extend_graph_with_cim("graph_lv_buses")
        self.pg_graph.create_building_graph()
        
        hv_mv_transformer_capacity = self.config["transformers"]["mv_hv"]["capacity_kva"]
        self.pg_graph.create_mv_graph(
            mv_lv_transformer_capacity, hv_mv_transformer_capacity
        )
        self.pg_graph.extend_graph_with_cim("graph_mv_buses")

        hv_substation_capacity: int = (
            len(self.pg_graph.labels_mv) if self.pg_graph.labels_mv is not None else 0
        ) * hv_mv_transformer_capacity
        self.pg_graph.create_hv_substation_graph(
            hv_mv_transformer_capacity, hv_substation_capacity
        )
        self.pg_graph.extend_graph_with_cim("graph_hv_buses")
        print("Geospatial multi-level grid generated.")

    def build_pandapower_model(self):
        pp_builder = PandapowerGridBuilder(power_grid=self.pg_graph, config=self.config)
        pp_builder.build_lv_buses_and_lines()
        pp_builder.build_mv_buses_and_lines()
        pp_builder.build_hv_buses_and_lines()
        pp_builder.build_loads_from_graph_buildings()
        pp_builder.build_lv_mv_power_transformers()
        pp_builder.build_mv_hv_power_transformers()
        pp_builder.connect_hv_bus_to_ext_grid()
        self.pp_net = pp_builder.get_pandapower_net()
        print("Pandapower electrical network built.")

    def inject_datagen_loads(self, cold_day, seed=42):
        # Clear any existing Timeseries controllers to prevent accumulation errors
        self.pp_net.controller.drop(self.pp_net.controller.index, inplace=True)
        
        # Topologically link thermal diversity blocks to the Low Voltage transformers
        labels_lv = self.pg_graph.labels_lv
        N_BLOCKS = len(set(labels_lv))
        buildings = make_buildings(N_BLOCKS, seed=seed)
        bld_results = simulate_buildings(buildings, cold_day["temp_air"])
        
        # We extract the 1-minute resolution kW load profiles
        profiles = [bld_results[i]["p_total_kw"].values for i in range(N_BLOCKS)]
        
        # DOWNSAMPLE to 15-minute intervals (96 steps) for performant daily simulation
        profiles_15min = [prof[::15] for prof in profiles]
        time_steps = len(profiles_15min[0])
        
        # Get mean area from the geospatial dataset to normalize scaling
        areas = self.pg_graph.building_data["Area (sq. meters)"].values
        mean_area = areas.mean() if len(areas) > 0 else 1.0

        # Build pandas DataFrame for ConstControl: columns = load.index, index = time_steps
        import pandas as pd
        p_mw_df = pd.DataFrame(index=range(time_steps), columns=self.pp_net.load.index)
        q_mvar_df = pd.DataFrame(index=range(time_steps), columns=self.pp_net.load.index)
        
        for idx in self.pp_net.load.index:
            building_idx = idx % len(areas)
            building_area = areas[building_idx] 
            area_scale = building_area / mean_area 
            
            # Map the building directly to its physically connected Low Voltage transformer neighborhood
            trafo_cluster_id = labels_lv[building_idx]
            prof = profiles_15min[trafo_cluster_id]
            
            # Array of MW scaled
            peak_mw = (prof / 50.0) * area_scale / 1000.0
            p_mw_df[idx] = peak_mw
            q_mvar_df[idx] = peak_mw * 0.1
            
        # Save raw building aggregation array for comparative plotting
        self.raw_datagen_p_mw = p_mw_df.sum(axis=1)
        
        # Initialize pandapower controllers
        from pandapower.timeseries import DFData
        from pandapower.control import ConstControl
        
        ds_p = DFData(p_mw_df)
        ds_q = DFData(q_mvar_df)
        
        ConstControl(self.pp_net, element='load', variable='p_mw', element_index=self.pp_net.load.index, data_source=ds_p, profile_name=self.pp_net.load.index)
        ConstControl(self.pp_net, element='load', variable='q_mvar', element_index=self.pp_net.load.index, data_source=ds_q, profile_name=self.pp_net.load.index)
        
        # print to keep terminal clean during 10 simulations

    def run_power_flow(self):
        from pandapower.timeseries import run_timeseries
        from pandapower.timeseries import OutputWriter
        
        # Initialize output writer to track extremes
        ow = OutputWriter(self.pp_net, time_steps=range(96))
        ow.log_variable('res_bus', 'vm_pu')
        ow.log_variable('res_line', 'loading_percent')
        ow.log_variable('res_trafo', 'loading_percent')
        ow.log_variable('res_ext_grid', 'p_mw')
        
        # Disable tracking output to prevent terminal noise
        run_timeseries(self.pp_net, time_steps=range(96), verbose=False)
        return ow

    def verify_grid_stats(self):
        print("\n====== Verification: Grid Statistics ======")
        
        # 1. Voltage Statistics
        vm_pu = self.pp_net.res_bus.vm_pu.dropna()
        min_v = vm_pu.min()
        max_v = vm_pu.max()
        under_voltage = (vm_pu < 0.95).sum() / len(vm_pu) * 100
        over_voltage = (vm_pu > 1.05).sum() / len(vm_pu) * 100
        
        print(f"Voltage (p.u.): Min={min_v:.3f}, Max={max_v:.3f}")
        if under_voltage > 0 or over_voltage > 0:
            print(f"  WARNING: {under_voltage:.1f}% buses < 0.95 p.u. | {over_voltage:.1f}% buses > 1.05 p.u.")
        else:
            print("  SUCCESS: All buses within 0.95 - 1.05 p.u. limits.")
            
        # 2. Line Loadings
        line_loading = self.pp_net.res_line.loading_percent.dropna()
        mean_line = line_loading.mean()
        max_line = line_loading.max()
        overloaded_lines = (line_loading > 100).sum()
        
        print(f"Line Loading (%): Mean={mean_line:.1f}%, Max={max_line:.1f}%")
        if overloaded_lines > 0:
            print(f"  WARNING: {overloaded_lines} lines are overloaded (>100% capacity)!")
        else:
            print("  SUCCESS: No lines are overloaded.")
            
        # 3. Transformer Loadings
        trafo_loading = self.pp_net.res_trafo.loading_percent.dropna()
        if len(trafo_loading) > 0:
            mean_trafo = trafo_loading.mean()
            max_trafo = trafo_loading.max()
            overloaded_trafos = (trafo_loading > 100).sum()
            
            print(f"Trafo Loading (%): Mean={mean_trafo:.1f}%, Max={max_trafo:.1f}%")
            if overloaded_trafos > 0:
                print(f"  WARNING: {overloaded_trafos} transformers are overloaded (>100% capacity)!")
            else:
                print("  SUCCESS: No transformers are overloaded.")
        print("===========================================\n")

    def visualize_results(self):
        self.plotter = GridPlotter(self.pg_graph)
        voltage_map = self.plotter.plot_voltage_deviations_folium(self.pp_net)
        voltage_map_output_path = os.path.join(
            self.output_dir, "voltage_deviations_map_datagen.html"
        )
        voltage_map.save(voltage_map_output_path)
        print(f"Voltage deviations HTML map saved to {voltage_map_output_path}")
        
        self.export_results_to_geojson()

    def plot_stochastic_results(self):
        print("\n====== Generating Stochastic Probabilistic Bounds ======")
        import matplotlib.pyplot as plt
        import numpy as np

        fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)
        
        time_axis = np.arange(0, 24, 0.25)
        
        # Combine list of arrays into 2D tensor arrays (N_REALIZATIONS, 96)
        ext_arr = np.array(self.mc_ext_p_mw)
        ext_mean = ext_arr.mean(axis=0)
        ext_5 = np.percentile(ext_arr, 5, axis=0)
        ext_95 = np.percentile(ext_arr, 95, axis=0)
        
        # 1. Substation Power Profile (Stochastic Trajectories)
        # Plot individual trajectories first so they are under the mean
        for sim_idx, ext_traj in enumerate(ext_arr):
            # Only add the label for the first trajectory to avoid legend clutter
            label = "Individual Realizations" if sim_idx == 0 else None
            ax1.plot(time_axis, ext_traj, color="#3b5998", alpha=0.15, linewidth=1, label=label)
            
        ax1.plot(time_axis, ext_mean, label="Substation Import (Mean)", color="#2c3e50", linewidth=2.5)
        
        raw_arr = np.array(self.mc_raw_p_mw)
        ax1.plot(time_axis, raw_arr.mean(axis=0), label="Raw Datagen Aggregation (Mean)", color="gray", linestyle="--", linewidth=1.5)
        
        ax1.set_ylabel("Active Power [MW]", fontweight="bold")
        ax1.set_title(f"Stochastic Substation Demand ({len(ext_arr)} Realizations)", fontweight="bold")
        ax1.grid(True, alpha=0.3, linestyle="--")
        ax1.legend(loc="upper left")
        
        # 2. Maximum Line Congestion (Stochastic Trajectories)
        line_arr = np.array(self.mc_max_line)  # Already max spatial bounds per time step
        line_mean = line_arr.mean(axis=0)
        line_99 = np.percentile(line_arr, 99, axis=0) # 99th percentile hazard case
        
        # Plot individual congestion hazard trajectories
        for sim_idx, line_traj in enumerate(line_arr):
            label = "Individual Hazards" if sim_idx == 0 else None
            ax2.plot(time_axis, line_traj, color="#e67e22", alpha=0.2, linewidth=1.5, label=label)
            
        ax2.plot(time_axis, line_mean, label="Grid Expected Max Congestion (Mean)", color="#d35400", linewidth=3)
        ax2.plot(time_axis, line_99, label="Grid Extreme Congestion (99th Pct Constraint)", color="#c0392b", linewidth=2, linestyle="--")
        
        # 100% threshold
        ax2.axhline(100, color="black", linestyle=":", linewidth=2, label="Physical Capacity Limit (100%)")
        
        ax2.set_xlabel("Time of Day [Hours]", fontweight="bold")
        ax2.set_ylabel("Loading [%]", fontweight="bold")
        ax2.set_title("Probabilistic Grid Congestion Analytics", fontweight="bold")
        ax2.set_xticks(np.arange(0, 25, 4))
        ax2.grid(True, alpha=0.3, linestyle="--")
        ax2.legend(loc="upper left")
        
        plt.tight_layout()
        plot_path = os.path.join(self.output_dir, "stochastic_metrics.png")
        plt.savefig(plot_path, dpi=300)
        plt.close()
        
        print(f"Stochastic envelope visual plots saved to {plot_path}")

    def export_results_to_geojson(self):
        print("\n====== Exporting Results for Kepler.gl ======")
        import geopandas as gpd
        import pandas as pd
        import json
        from shapely.geometry import Point, LineString
        
        # 1. Parse Buses (Nodes) coordinates from geo column
        bus_details = self.pp_net.bus
        res_bus = self.pp_net.res_bus
        
        # Parse JSON from geo string if it exists
        if "geo" in bus_details.columns:
            def extract_coords(geo_str):
                try:
                    if pd.notna(geo_str):
                        data = json.loads(geo_str.replace("'", '"'))
                        return data.get("coordinates", [0, 0])
                except Exception:
                    pass
                return [0, 0]
                
            coords = bus_details["geo"].apply(extract_coords)
            bus_x = coords.apply(lambda c: c[0]) # Longitude
            bus_y = coords.apply(lambda c: c[1]) # Latitude
        else:
            # Fallback
            bus_x = pd.Series(0, index=bus_details.index)
            bus_y = pd.Series(0, index=bus_details.index)
        
        nodes = []
        for bus_idx in bus_details.index:
            x, y = bus_x.at[bus_idx], bus_y.at[bus_idx]
            vm_pu = res_bus.at[bus_idx, 'vm_pu'] if bus_idx in res_bus.index else None
            p_mw = res_bus.at[bus_idx, 'p_mw'] if bus_idx in res_bus.index else None
            bus_name = bus_details.at[bus_idx, 'name'] if bus_idx in bus_details.index else str(bus_idx)
            
            nodes.append({
                'geometry': Point(y, x), # GeoJSON expects (Longitude, Latitude)
                'bus_idx': int(bus_idx),
                'name': str(bus_name),
                'vm_pu': float(vm_pu) if pd.notna(vm_pu) else None,
                'p_mw': float(p_mw) if pd.notna(p_mw) else None
            })
            
        nodes_gdf = gpd.GeoDataFrame(nodes, crs="EPSG:4326")
        nodes_out_path = os.path.join(self.output_dir, "grid_nodes_results.geojson")
        nodes_gdf.to_file(nodes_out_path, driver="GeoJSON")
        print(f"  Exported {len(nodes_gdf)} Nodes to {nodes_out_path}")
        
        # 2. Export Lines (Edges)
        lines = []
        res_line = self.pp_net.res_line
        line_details = self.pp_net.line
        
        for line_idx in line_details.index:
            from_bus = line_details.at[line_idx, 'from_bus']
            to_bus = line_details.at[line_idx, 'to_bus']
            loading = res_line.at[line_idx, 'loading_percent'] if line_idx in res_line.index else None
            
            # GeoJSON strictly requires (Longitude, Latitude), so we pass (y, x)
            p1 = (bus_y.at[from_bus], bus_x.at[from_bus]) if from_bus in bus_x.index else None
            p2 = (bus_y.at[to_bus], bus_x.at[to_bus]) if to_bus in bus_x.index else None
            
            if p1 and p2:
                lines.append({
                    'geometry': LineString([p1, p2]),
                    'line_idx': int(line_idx),
                    'loading_percent': float(loading) if pd.notna(loading) else None
                })
                
        if lines:
            lines_gdf = gpd.GeoDataFrame(lines, crs="EPSG:4326")
            lines_out_path = os.path.join(self.output_dir, "grid_lines_results.geojson")
            lines_gdf.to_file(lines_out_path, driver="GeoJSON")
            print(f"  Exported {len(lines_gdf)} Lines to {lines_out_path}")


def main() -> None:
    """
    Script to integrate Datagen temporal simulation with Gridalyn spatial grids,
    running a single-snapshot peak power flow analysis.
    """
    input_file = str(datasets.get_dataset_path("buildings_inside_polygon.geojson"))
    analysis = PowerFlowAnalysisDatagen(input_file=input_file)
    analysis.run()


if __name__ == "__main__":
    main()
