"""Generate the deterministic annual 8760h profiles for ev_hosting_flex.

Stage 3 of the workflow (PROF-01/02/03). Reads the Phase-8/08.1 topology cache
JSON sidecars (per-bus nameplate kW, per-bus building count, the radial
downstream map, the feeder selection) and the ``_profiles.py`` numeric kernel to
emit two float64 parquet artifacts plus a governed report:

* ``data/base_load_8760.parquet`` — ``(n_feeder_bus, 8760)`` per-bus winter-peaked
  base building load (the addressable-per-bus envelope the downstream-sum proxy
  aggregates, D-02);
* ``data/ev_load_unit.parquet`` — ``(n_feeder_bus, 8760)`` per-EV evening-window
  unit draw, addressable per bus and scaled by ``node_ev_count`` at sweep time;
* ``reports/annual_profiles_report.json`` — canonical platform report via
  ``script.write_report`` (GOV-02; never hand-written report JSON).

**Divergence from ROADMAP-#1.** ROADMAP success-criterion #1 specifies the base
load should be driven by ``download_tmy()`` + ``GridLoadFacade.generate_loads``
(a weather-driven SDK path). This stage deliberately implements the **parametric
winter envelope** (Phase-9 CONTEXT.md D-01), which **supersedes** that wording.
Rationale: the study headline is *relative* hosting expansion, not weather-
accurate absolute load; the parametric envelope has no RNG and no PVGIS/``"auto"``
network dependency, so it is trivially reproducible to 1e-6 (D-12) — exactly the
REPRO-04 defect the weather path risks. The divergence note is written into both
the report ``summary`` and ``validation.warnings`` so verify-phase reads the
criterion's intent (a winter-peaked, reproducible, pinned-input 8760h base load),
which the parametric envelope satisfies.

GUARD-02: NO module-scope ``import pandapower`` / ``geopandas``. This stage reads
ONLY the JSON cache sidecars (never ``pp_net_cache.pkl``), so it stays
pandapower-free; pandapower enters the study only at Phase-11 AC validation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).parents[4]
sys.path.insert(0, str(ROOT))

from projects.ev_hosting_flex.scripts._profiles import (  # noqa: E402
    base_load_8760,
    ev_unit_profile,
)
from projects.ev_hosting_flex.scripts.config import (  # noqa: E402
    DTYPE,
    PROJECT_CACHE_DIR,
    ROUND_DECIMALS,
)

_DIVERGENCE_NOTE = (
    "Divergence from ROADMAP-#1: the base building load is generated by the "
    "parametric winter-peaked envelope (Phase-9 D-01), which supersedes the "
    "ROADMAP download_tmy + GridLoadFacade weather path. Rationale: the headline "
    "is relative hosting expansion (not weather-accurate absolute load), and the "
    "parametric path has no RNG and no PVGIS/'auto' network dependency, giving "
    "trivial 1e-6 reproducibility (D-12). The criterion's intent (a winter-peaked, "
    "reproducible, pinned-input 8760h base load) is satisfied."
)


def _load_json(path: Path) -> dict:
    """Load a required JSON cache sidecar, failing loudly if it is missing.

    Args:
        path: Path to the JSON sidecar produced by the stage-2 topology cache.

    Returns:
        The parsed JSON mapping.

    Raises:
        FileNotFoundError: If the sidecar is absent (stale/incomplete cache).
    """
    if not path.is_file():
        raise FileNotFoundError(
            f"ev_hosting_flex stage 3 requires the topology cache sidecar "
            f"{path.name} at {path}, but it is missing. Remediation: re-run "
            "stage 2 (prepare_topology_cache.py) to regenerate the load-aware "
            "cache before generating annual profiles."
        )
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def _summarize_array(arr: np.ndarray) -> dict[str, object]:
    """Return deterministic sum/max/sha256 stats over a rounded float64 array.

    The ``content_sha256`` over the canonical-bytes array is the byte-stability
    tripwire for the Phase-12 regression baseline (D-12).

    Args:
        arr: A rounded float64 array.

    Returns:
        A mapping with ``sum``, ``max``, ``shape`` and ``content_sha256``.
    """
    canonical = np.ascontiguousarray(arr, dtype="float64")
    # Canonicalize signed zero so -0.0 and 0.0 hash identically (REPRO).
    canonical = canonical + 0.0
    digest = hashlib.sha256(canonical.tobytes()).hexdigest()
    return {
        "sum": round(float(canonical.sum()), ROUND_DECIMALS),
        "max": round(float(canonical.max()), ROUND_DECIMALS),
        "shape": list(canonical.shape),
        "content_sha256": digest,
    }


def derive_annual_profiles(cache_dir: Path, data_dir: Path) -> dict[str, object]:
    """Derive + persist the per-bus annual base + EV unit profiles.

    Reads the topology cache sidecars (pandapower-free), restricts to the selected
    feeder's load buses (intersection of its downstream set with the load-bus
    sidecars, A3), builds the SORTED per-bus nameplate + building-count arrays,
    calls the ``_profiles.py`` kernel, rounds to ``ROUND_DECIMALS``, and writes the
    two float64 parquet artifacts indexed by the sorted bus ids.

    Args:
        cache_dir: Directory holding the stage-2 JSON cache sidecars.
        data_dir: Directory the parquet artifacts are written to.

    Returns:
        A mapping with ``artifact_paths`` and a ``summary`` dict.
    """
    nameplate_kw = _load_json(cache_dir / "node_nameplate_kw.json")
    building_count = _load_json(cache_dir / "node_building_count.json")
    downstream = _load_json(cache_dir / "downstream_bus_map.json")
    feeder = _load_json(cache_dir / "feeder_selection.json")

    # Read the feeder key at runtime — never hardcode the transformer index (T-09-01).
    feeder_idx = int(feeder["feeder_transformer_idx"])
    feeder_key = f"transformer:{feeder_idx}"
    if feeder_key not in downstream:
        raise ValueError(
            f"ev_hosting_flex stage 3: feeder key {feeder_key!r} from "
            "feeder_selection.json is absent from downstream_bus_map.json. "
            "Remediation: regenerate the topology cache (stage 2) so the feeder "
            "selection and downstream map come from the same net."
        )

    # A3: restrict to the feeder's downstream LOAD buses (intersection with the
    # nameplate sidecar keys), in deterministic SORTED bus order.
    load_buses = {int(b) for b in nameplate_kw}
    feeder_buses = sorted(set(downstream[feeder_key]) & load_buses)
    if not feeder_buses:
        raise ValueError(
            f"ev_hosting_flex stage 3: the selected feeder {feeder_key} has no "
            "downstream load buses in node_nameplate_kw.json. Remediation: verify "
            "the load-aware topology cache was built from the expected feeder."
        )

    nameplate_arr = np.array(
        [nameplate_kw[str(b)] for b in feeder_buses], dtype=DTYPE
    )
    building_arr = np.array(
        [int(building_count[str(b)]) for b in feeder_buses], dtype=np.int64
    )

    base = np.round(base_load_8760(nameplate_arr), ROUND_DECIMALS).astype("float64")
    ev_unit = ev_unit_profile()
    ev_per_bus = np.round(
        np.broadcast_to(ev_unit, (len(feeder_buses), ev_unit.shape[0])),
        ROUND_DECIMALS,
    ).astype("float64")

    data_dir.mkdir(parents=True, exist_ok=True)
    columns = [f"h{h}" for h in range(base.shape[1])]
    base_path = data_dir / "base_load_8760.parquet"
    ev_path = data_dir / "ev_load_unit.parquet"
    pd.DataFrame(base, index=feeder_buses, columns=columns).astype(
        "float64"
    ).to_parquet(base_path)
    pd.DataFrame(ev_per_bus, index=feeder_buses, columns=columns).astype(
        "float64"
    ).to_parquet(ev_path)

    return {
        "artifact_paths": [base_path, ev_path],
        "summary": {
            "n_feeder_bus": len(feeder_buses),
            "feeder_key": feeder_key,
            "feeder_transformer_idx": feeder_idx,
            "total_nameplate_kw": round(float(nameplate_arr.sum()), ROUND_DECIMALS),
            "total_building_count": int(building_arr.sum()),
            "base_load": _summarize_array(base),
            "ev_load_unit": _summarize_array(ev_per_bus),
            "divergence_note": _DIVERGENCE_NOTE,
        },
    }


def run_stage(
    *,
    cache_dir: Path = PROJECT_CACHE_DIR,
    data_dir: Path | None = None,
) -> dict[str, object]:
    """Run the full annual-profiles stage: derive + parquet + governed report.

    Args:
        cache_dir: Cache directory holding the stage-2 sidecars.
        data_dir: Output data directory override (defaults to the project's).

    Returns:
        The platform report payload written via ``script.write_report``.
    """
    from gridalyn.projects.scripting import project_script

    script = project_script()
    effective_cache_dir = (
        script.cache_dir if cache_dir == PROJECT_CACHE_DIR else cache_dir
    )
    effective_data_dir = data_dir if data_dir is not None else script.data_dir

    derived = derive_annual_profiles(effective_cache_dir, effective_data_dir)
    artifact_paths = derived["artifact_paths"]  # type: ignore[assignment]
    summary = derived["summary"]  # type: ignore[assignment]

    return script.write_report(
        "annual_profiles_report",
        artifacts=[script.file_reference(p) for p in artifact_paths],
        summary=summary,
        validation={
            "valid": True,
            "errors": [],
            "warnings": [_DIVERGENCE_NOTE],
        },
    )


def main() -> None:
    """CLI entry point for the annual-profiles stage."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache-dir", type=Path, default=PROJECT_CACHE_DIR)
    parser.add_argument("--data-dir", type=Path)
    args = parser.parse_args()

    report = run_stage(cache_dir=args.cache_dir, data_dir=args.data_dir)
    summary = report.get("summary", {})
    print(
        "Generated annual profiles + report: "
        f"feeder_key={summary.get('feeder_key')}, "
        f"n_feeder_bus={summary.get('n_feeder_bus')}"
    )


if __name__ == "__main__":
    main()
