"""Reusable real-time market runner for prosumer battery dispatch."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
import pandapower as pp

from gridalyn.simulation import (
    apply_battery_dispatch_to_pandapower,
    apply_pv_generation_to_pandapower,
    configure_headless_matplotlib,
)


@dataclass(frozen=True)
class ProsumerRealtimeMarketConfig:
    """Configuration for a rolling-horizon prosumer battery market."""

    interval_minutes: int
    interval_count: int
    import_limit_mw: float
    forecast_horizon_intervals: int
    load_multipliers: tuple[float, ...]
    pv_factors: tuple[float, ...]
    load_forecast_bias_by_lead: tuple[float, ...]
    pv_forecast_bias_by_lead: tuple[float, ...]
    reserve_fraction: float = 0.55
    locational_credit_usd_per_mwh: float = 2.0
    scarcity_adder_usd_per_mwh: float = 6.0

    @property
    def dt_h(self) -> float:
        return self.interval_minutes / 60.0


@dataclass(frozen=True)
class ProsumerRealtimeMarketResult:
    """Tables generated by a prosumer real-time market run."""

    clearing: pd.DataFrame
    dispatch: pd.DataFrame
    forecast: pd.DataFrame
    offers: pd.DataFrame
    powerflow: pd.DataFrame


def _market_timestamps(config: ProsumerRealtimeMarketConfig) -> list[str]:
    return [f"RT-{index:02d}" for index in range(config.interval_count)]


def build_interval_forecast(
    issue_index: int,
    *,
    base_load_mw: float,
    total_pv_capacity_mw: float,
    config: ProsumerRealtimeMarketConfig,
) -> pd.DataFrame:
    """Create a rolling forecast issued before clearing one market interval."""
    rows = []
    for lead in range(config.forecast_horizon_intervals):
        target_index = min(issue_index + lead, config.interval_count - 1)
        load_multiplier = config.load_multipliers[target_index] * (
            1.0 + config.load_forecast_bias_by_lead[lead]
        )
        pv_factor = max(
            config.pv_factors[target_index]
            * (1.0 + config.pv_forecast_bias_by_lead[lead]),
            0.0,
        )
        pv_generation_mw = total_pv_capacity_mw * pv_factor
        import_mw = base_load_mw * load_multiplier - pv_generation_mw
        rows.append(
            {
                "issue_interval_index": issue_index,
                "issue_interval_id": f"RT-{issue_index:02d}",
                "target_interval_index": target_index,
                "target_interval_id": f"RT-{target_index:02d}",
                "lead_interval": lead,
                "forecast_load_multiplier": load_multiplier,
                "forecast_pv_factor": pv_factor,
                "forecast_pv_generation_mw": pv_generation_mw,
                "forecast_import_mw": import_mw,
                "forecast_required_reduction_mw": max(
                    import_mw - config.import_limit_mw,
                    0.0,
                ),
            }
        )
    return pd.DataFrame(rows)


def clear_prosumer_interval(
    prosumers: pd.DataFrame,
    soc: dict[str, float],
    forecast: pd.DataFrame,
    *,
    config: ProsumerRealtimeMarketConfig,
) -> tuple[list[dict], list[dict], float, float, float | None]:
    """Clear one interval of the rolling-horizon prosumer market."""
    dispatch_rows: list[dict] = []
    offers: list[dict] = []
    current = forecast.loc[forecast["lead_interval"] == 0].iloc[0]
    required_mw = float(current["forecast_required_reduction_mw"])
    remaining = max(required_mw, 0.0)
    accepted_offer_prices: list[float] = []

    total_power_mw = float(prosumers["battery_power_mw"].sum())
    future_required_mwh = float(
        (
            forecast.loc[forecast["lead_interval"] > 0, "forecast_required_reduction_mw"]
            * config.dt_h
        ).sum()
    )
    usable_energy_mwh = sum(
        max(soc[str(row.prosumer_id)] - float(row.min_soc_mwh), 0.0)
        for row in prosumers.itertuples(index=False)
    )
    scarcity_ratio = future_required_mwh / max(usable_energy_mwh, 1e-9)

    cleared_by_prosumer = {
        str(row.prosumer_id): 0.0 for row in prosumers.itertuples(index=False)
    }
    offer_rows = []
    for row in prosumers.itertuples(index=False):
        prosumer_id = str(row.prosumer_id)
        future_reserve_mwh = (
            future_required_mwh
            * (float(row.battery_power_mw) / max(total_power_mw, 1e-9))
            * config.reserve_fraction
        )
        available_energy_mwh = max(
            soc[prosumer_id] - float(row.min_soc_mwh) - future_reserve_mwh,
            0.0,
        )
        offered_quantity_mw = min(
            float(row.battery_power_mw),
            available_energy_mwh / config.dt_h,
        )
        max_bus_id = float(prosumers["bus_id"].max())
        locational_priority = (
            float(row.bus_id) / max_bus_id if max_bus_id > 0 else 0.0
        )
        submitted_price = (
            float(row.offer_price_usd_per_mwh)
            + config.scarcity_adder_usd_per_mwh * scarcity_ratio
        )
        network_adjusted_price = (
            submitted_price - config.locational_credit_usd_per_mwh * locational_priority
        )
        offer_rows.append(
            {
                "prosumer_id": prosumer_id,
                "bus_id": int(row.bus_id),
                "submitted_offer_price_usd_per_mwh": submitted_price,
                "network_adjusted_bid_price_usd_per_mwh": network_adjusted_price,
                "offered_quantity_mw": offered_quantity_mw,
                "future_reserve_mwh": future_reserve_mwh,
                "forecast_scarcity_ratio": scarcity_ratio,
            }
        )

    offer_book = pd.DataFrame(offer_rows).sort_values(
        ["network_adjusted_bid_price_usd_per_mwh", "prosumer_id"]
    )
    for row in offer_book.itertuples(index=False):
        prosumer_id = str(row.prosumer_id)
        dispatch_mw = min(float(row.offered_quantity_mw), remaining)
        if dispatch_mw > 0:
            soc[prosumer_id] -= dispatch_mw * config.dt_h
            remaining -= dispatch_mw
            accepted_offer_prices.append(float(row.submitted_offer_price_usd_per_mwh))
            cleared_by_prosumer[prosumer_id] = dispatch_mw
        if remaining <= 1e-9:
            break

    clearing_price = max(accepted_offer_prices) if accepted_offer_prices else None
    cleared_cost = sum(cleared_by_prosumer.values()) * config.dt_h * float(
        clearing_price or 0.0
    )

    for row in prosumers.sort_values("prosumer_id").itertuples(index=False):
        prosumer_id = str(row.prosumer_id)
        offer = offer_book.loc[offer_book["prosumer_id"] == prosumer_id].iloc[0]
        dispatch_mw = float(cleared_by_prosumer[prosumer_id])
        dispatch_rows.append(
            {
                "prosumer_id": prosumer_id,
                "bus_id": int(row.bus_id),
                "submitted_offer_price_usd_per_mwh": float(
                    offer.submitted_offer_price_usd_per_mwh
                ),
                "network_adjusted_bid_price_usd_per_mwh": float(
                    offer.network_adjusted_bid_price_usd_per_mwh
                ),
                "market_clearing_price_usd_per_mwh": clearing_price,
                "settlement_price_usd_per_mwh": clearing_price if dispatch_mw > 0 else 0.0,
                "dispatch_mw": dispatch_mw,
                "dispatch_mwh": dispatch_mw * config.dt_h,
                "payment_usd": dispatch_mw * config.dt_h * float(clearing_price or 0.0),
                "soc_mwh_after": float(soc[prosumer_id]),
            }
        )
        offer_dict = offer.to_dict()
        offer_dict["accepted_mw"] = dispatch_mw
        offer_dict["market_clearing_price_usd_per_mwh"] = clearing_price
        offers.append(offer_dict)
    return dispatch_rows, offers, required_mw - remaining, cleared_cost, clearing_price


def run_prosumer_powerflow(
    *,
    build_feeder: Callable[[], pp.pandapowerNet],
    load_multiplier: float,
    prosumers: pd.DataFrame,
    pv_factor: float,
    dispatch: pd.DataFrame,
) -> dict[str, float | bool]:
    """Run feeder verification for one prosumer market interval."""
    net = build_feeder()
    net.load["p_mw"] = net.load["p_mw"] * load_multiplier
    net.load["q_mvar"] = net.load["q_mvar"] * load_multiplier

    apply_pv_generation_to_pandapower(net, prosumers, pv_factor=pv_factor)
    apply_battery_dispatch_to_pandapower(net, dispatch)

    pp.runpp(net, algorithm="nr", init="auto")
    return {
        "converged": bool(net.converged),
        "min_voltage_pu": float(net.res_bus.vm_pu.min()),
        "max_voltage_pu": float(net.res_bus.vm_pu.max()),
        "max_line_loading_percent": float(net.res_line.loading_percent.max()),
        "line_loss_mw": float(net.res_line.pl_mw.sum()),
    }


def run_prosumer_realtime_market(
    *,
    prosumers: pd.DataFrame,
    build_feeder: Callable[[], pp.pandapowerNet],
    config: ProsumerRealtimeMarketConfig,
) -> ProsumerRealtimeMarketResult:
    """Run rolling-horizon clearing, dispatch, and feeder verification."""
    base_load_mw = float(build_feeder().load.p_mw.sum())
    soc = {
        str(row.prosumer_id): float(row.initial_soc_mwh)
        for row in prosumers.itertuples(index=False)
    }
    total_pv_capacity_mw = float(prosumers["pv_capacity_mw"].sum())

    clearing_rows: list[dict] = []
    dispatch_rows: list[dict] = []
    forecast_rows: list[dict] = []
    offer_rows: list[dict] = []
    powerflow_rows: list[dict] = []

    for index, interval_id in enumerate(_market_timestamps(config)):
        load_multiplier = config.load_multipliers[index]
        pv_factor = config.pv_factors[index]
        pv_mw = float((prosumers["pv_capacity_mw"] * pv_factor).sum())
        import_before_mw = base_load_mw * load_multiplier - pv_mw
        forecast = build_interval_forecast(
            index,
            base_load_mw=base_load_mw,
            total_pv_capacity_mw=total_pv_capacity_mw,
            config=config,
        )
        forecast_rows.extend(forecast.to_dict(orient="records"))
        current_forecast = forecast.loc[forecast["lead_interval"] == 0].iloc[0]
        required_mw = float(current_forecast["forecast_required_reduction_mw"])
        interval_dispatch, interval_offers, cleared_mw, cleared_cost, clearing_price = (
            clear_prosumer_interval(prosumers, soc, forecast, config=config)
        )
        interval_dispatch_df = pd.DataFrame(interval_dispatch)
        powerflow = run_prosumer_powerflow(
            build_feeder=build_feeder,
            load_multiplier=load_multiplier,
            prosumers=prosumers,
            pv_factor=pv_factor,
            dispatch=interval_dispatch_df,
        )
        import_after_mw = import_before_mw - cleared_mw

        clearing_rows.append(
            {
                "interval_id": interval_id,
                "interval_index": index,
                "load_multiplier": load_multiplier,
                "pv_factor": pv_factor,
                "pv_generation_mw": pv_mw,
                "import_before_mw": import_before_mw,
                "forecast_import_mw": float(current_forecast["forecast_import_mw"]),
                "forecast_required_reduction_mw": required_mw,
                "required_reduction_mw": required_mw,
                "cleared_mw": cleared_mw,
                "unserved_mw": max(required_mw - cleared_mw, 0.0),
                "import_after_mw": import_after_mw,
                "market_clearing_price_usd_per_mwh": clearing_price,
                "cleared_cost_usd": cleared_cost,
            }
        )
        for row in interval_dispatch:
            row["interval_id"] = interval_id
            row["interval_index"] = index
            dispatch_rows.append(row)
        for row in interval_offers:
            row["interval_id"] = interval_id
            row["interval_index"] = index
            offer_rows.append(row)
        powerflow["interval_id"] = interval_id
        powerflow["interval_index"] = index
        powerflow_rows.append(powerflow)

    return ProsumerRealtimeMarketResult(
        clearing=pd.DataFrame(clearing_rows),
        dispatch=pd.DataFrame(dispatch_rows),
        forecast=pd.DataFrame(forecast_rows),
        offers=pd.DataFrame(offer_rows),
        powerflow=pd.DataFrame(powerflow_rows),
    )


def build_prosumer_realtime_market_summary(
    result: ProsumerRealtimeMarketResult,
    *,
    config: ProsumerRealtimeMarketConfig,
) -> dict[str, float | int | str]:
    """Build the report summary for a prosumer real-time market result."""
    clearing = result.clearing
    dispatch = result.dispatch
    powerflow = result.powerflow
    return {
        "algorithm": "rolling_horizon_uniform_price_auction",
        "published_method_family": (
            "transactive_energy_real_time_uniform_price_auction_with_mpc_forecast_horizon"
        ),
        "forecast_horizon_intervals": config.forecast_horizon_intervals,
        "interval_count": int(len(clearing)),
        "interval_minutes": config.interval_minutes,
        "prosumer_count": int(dispatch["prosumer_id"].nunique()),
        "import_limit_mw": config.import_limit_mw,
        "peak_import_before_mw": float(clearing["import_before_mw"].max()),
        "peak_import_after_mw": float(clearing["import_after_mw"].max()),
        "total_required_mwh": float(
            (clearing["required_reduction_mw"] * config.dt_h).sum()
        ),
        "total_cleared_mwh": float((clearing["cleared_mw"] * config.dt_h).sum()),
        "unserved_reduction_mwh": float((clearing["unserved_mw"] * config.dt_h).sum()),
        "total_market_cost_usd": float(clearing["cleared_cost_usd"].sum()),
        "min_voltage_after_pu": float(powerflow["min_voltage_pu"].min()),
        "max_line_loading_after_percent": float(powerflow["max_line_loading_percent"].max()),
    }


def write_prosumer_market_dispatch_figure(
    clearing: pd.DataFrame,
    path: Path | str,
    *,
    import_limit_mw: float,
) -> Path:
    """Write the standard prosumer real-time market dispatch figure."""
    configure_headless_matplotlib()
    import matplotlib.pyplot as plt

    figure_path = Path(path)
    figure_path.parent.mkdir(parents=True, exist_ok=True)
    x = range(len(clearing))
    fig, ax = plt.subplots(figsize=(9.4, 4.8))
    ax.plot(
        x,
        clearing["import_before_mw"],
        marker="o",
        linewidth=1.8,
        label="Import before",
    )
    ax.plot(
        x,
        clearing["import_after_mw"],
        marker="o",
        linewidth=1.8,
        label="Import after",
    )
    ax.axhline(
        import_limit_mw,
        color="#c0392b",
        linestyle="--",
        linewidth=1.2,
        label="Import limit",
    )
    ax.bar(
        x,
        clearing["cleared_mw"],
        alpha=0.26,
        color="#2ca02c",
        label="Cleared battery MW",
    )
    ax.set_title("Prosumer Battery Real-Time Market")
    ax.set_xlabel("5-minute interval")
    ax.set_ylabel("Power [MW]")
    ax.set_xticks(list(x))
    ax.set_xticklabels(clearing["interval_id"], rotation=45, ha="right")
    ax.grid(True, alpha=0.28)
    ax.legend(loc="best", fontsize=8)
    fig.tight_layout()
    fig.savefig(figure_path, dpi=160)
    plt.close(fig)
    return figure_path


__all__ = [
    "ProsumerRealtimeMarketConfig",
    "ProsumerRealtimeMarketResult",
    "build_interval_forecast",
    "build_prosumer_realtime_market_summary",
    "clear_prosumer_interval",
    "run_prosumer_powerflow",
    "run_prosumer_realtime_market",
    "write_prosumer_market_dispatch_figure",
]
